# Generated by Django 5.1.7 on 2025-05-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Входные данные для тестирования')),
                ('expected_output', models.TextField(help_text='Ожидаемый вывод')),
                ('is_sample', models.BooleanField(default=False, help_text='Является ли этот тест образцом')),
                ('order', models.IntegerField(default=0, help_text='Порядок выполнения тестов')),
                ('points', models.IntegerField(default=1, help_text='Баллы за прохождение теста')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problem.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('SE', 'System Error')], max_length=3)),
                ('execution_time', models.IntegerField(blank=True, help_text='Время выполнения в миллисекундах', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Использованная память в килобайтах', null=True)),
                ('output', models.TextField(blank=True, help_text='Фактический вывод программы')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке, если есть')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='submission.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.testcase')),
            ],
            options={
                'unique_together': {('submission', 'test_case')},
            },
        ),
    ]
